version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for the report-to-backend action
  - package-ecosystem: "npm"
    directory: "/.github/workflows/actions/report-to-backend"
    schedule:
      interval: "weekly"
